---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1kc427cnqsn0hzuguemc0vwkzequh664auez2z9cewunzvsfc54cqvp9q2n"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1kc427cnqsn0hzuguemc0vwkzequh664auez2z9cewunzvsfc54cqvp9q2n"
